version: '3.7'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE_NAME}
    volumes:
      - ./docker/resources/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/volumes/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "3307:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOSTS: mysql
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/volumes/phpmyadmin/sessions:/sessions
    depends_on:
      - mysql

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    restart: always
    ports:
      - "8080:8080"
    environment:
      TZ: Asia/Tokyo
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    volumes:
      - ./docker/volumes/keycloak:/opt/keycloak/data/h2
    command:
      - start-dev

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /tmp
    volumes:
      - ./docker/volumes/mailhog:/tmp
