pkgname  = "dao"
output   = "generated/interfaces/database/dao"
wipe     = true
no-tests = true
add-enum-types = true

[mysql]
  dbname  = "test"
  host    = "localhost"
  port    = 3306
  user    = "test"
  pass    = "password"
  sslmode = "false"
  blacklist = ["schema_migrations"]
