---
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'codelab-monitor'

rule_files:
  - '/etc/prometheus/alert_rules.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets: [alertmanager:9093]

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ["prometheus:9090"]
  - job_name: 'sample-task-api-go'
    static_configs:
      - targets: ["host.docker.internal:1323"]
